package org.jloco.locos.config;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Duration;
import java.util.Map;
import org.jloco.locos.auth.PasswordScheme;
import org.jloco.locos.login.ClientVersion;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

class ConfigLoaderTest {

    @TempDir
    Path directory;

    /** The file JLoco-Game/config/login.config.properties, as generated by the previous versions. */
    private static final String LEGACY_FILE = """
            # JLoco - Login. By Locos.
            #Auto-Generated Config File

            #System
            system.server.exchange.ip jloco_login
            system.server.exchange.port 666
            system.server.exchange.key ChangeMeYn2kjibddFAWtnPJ2AFlL8WXmohJMCvigQggaEypa5E=

            #Login server
            system.server.login.port 450
            system.server.login.version 1.39.8e

            database.login.host jloco_mariadb
            database.login.port 3306
            database.login.user root
            database.login.pass secret
            database.login.name jloco_login
            """;

    private Path write(String content) throws IOException {
        Path file = directory.resolve("login.config.properties");
        Files.writeString(file, content, StandardCharsets.UTF_8);
        return file;
    }

    @Test
    void readsTheExistingConfigurationFiles() throws IOException {
        LoginConfig config = ConfigLoader.load(write(LEGACY_FILE), Map.of());

        assertThat(config.exchange())
                .isEqualTo(new LoginConfig.Exchange(
                        "jloco_login", 666, "ChangeMeYn2kjibddFAWtnPJ2AFlL8WXmohJMCvigQggaEypa5E="));
        assertThat(config.login().port()).isEqualTo(450);
        assertThat(config.login().minimumClientVersion()).isEqualTo(new ClientVersion(1, 39, 8, true));
        assertThat(config.login().connectionsPerMinute()).isEqualTo(30);
        assertThat(config.login().idleTimeout()).isEqualTo(Duration.ofMinutes(5));
        assertThat(config.database())
                .isEqualTo(new LoginConfig.Database("jloco_mariadb", 3306, "root", "secret", "jloco_login"));
        assertThat(config.database().jdbcUrl()).isEqualTo("jdbc:mariadb://jloco_mariadb:3306/jloco_login");
        assertThat(config.database().toString()).doesNotContain("secret");
        assertThat(config.passwordScheme()).isEqualTo(PasswordScheme.LEGACY);
    }

    @Test
    void environmentOverridesTheFile() throws IOException {
        LoginConfig config = ConfigLoader.load(
                write(LEGACY_FILE),
                Map.of(
                        "JLOCO_LOGIN_DATABASE_LOGIN_PASS", "from-env",
                        "JLOCO_LOGIN_SYSTEM_SERVER_LOGIN_PASSWORD_SCHEME", "pbkdf2"));
        assertThat(config.database().password()).isEqualTo("from-env");
        assertThat(config.passwordScheme()).isEqualTo(PasswordScheme.PBKDF2);
    }

    @Test
    void theSampleIsAValidConfiguration() throws IOException {
        LoginConfig config = ConfigLoader.load(write(ConfigLoader.sample()), Map.of());
        assertThat(config.login().port()).isEqualTo(450);
    }

    @Test
    void listsEveryProblemAtOnce() throws IOException {
        Path file = write("""
                system.server.exchange.port 99999
                system.server.exchange.key c2hvcnQ=
                system.server.login.port 450
                system.server.login.version 1.39
                system.server.login.password.scheme argon2
                database.login.port 3306
                """);
        assertThatThrownBy(() -> ConfigLoader.load(file, Map.of()))
                .isInstanceOf(ConfigException.class)
                .hasMessageContaining("system.server.exchange.ip is missing")
                .hasMessageContaining("system.server.exchange.port must be a port number")
                .hasMessageContaining("system.server.exchange.key must be base64 of at least 32 bytes")
                .hasMessageContaining("system.server.login.version must look like 1.39.8e")
                .hasMessageContaining("system.server.login.password.scheme must be legacy or pbkdf2")
                .hasMessageContaining("database.login.host is missing")
                .hasMessageContaining("--write-sample-config");
    }

    @Test
    void aMissingFileIsFineWhenTheEnvironmentHasEverything() {
        Map<String, String> environment = Map.of(
                "JLOCO_LOGIN_SYSTEM_SERVER_EXCHANGE_IP", "0.0.0.0",
                "JLOCO_LOGIN_SYSTEM_SERVER_EXCHANGE_PORT", "666",
                "JLOCO_LOGIN_SYSTEM_SERVER_EXCHANGE_KEY", "ChangeMeYn2kjibddFAWtnPJ2AFlL8WXmohJMCvigQggaEypa5E=",
                "JLOCO_LOGIN_SYSTEM_SERVER_LOGIN_PORT", "450",
                "JLOCO_LOGIN_SYSTEM_SERVER_LOGIN_VERSION", "1.39.8e",
                "JLOCO_LOGIN_DATABASE_LOGIN_HOST", "db",
                "JLOCO_LOGIN_DATABASE_LOGIN_PORT", "3306",
                "JLOCO_LOGIN_DATABASE_LOGIN_USER", "login",
                "JLOCO_LOGIN_DATABASE_LOGIN_NAME", "jloco_login");
        LoginConfig config = ConfigLoader.load(directory.resolve("absent.properties"), environment);
        assertThat(config.database().host()).isEqualTo("db");
        assertThat(config.database().password()).isEmpty();
    }
}
